In [1]:
# import pytorch
import torch


/home/codespace/.python/current/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# create a tensor
x = torch.tensor([1, 2, 3])
print(x)
# create a tensor with random values
x = torch.rand(2, 2)
print(x)
# create a tensor with zeros
x = torch.zeros(2, 2)
print(x)


tensor([1, 2, 3])
tensor([[0.2958, 0.9478],
        [0.7673, 0.7868]])
tensor([[0., 0.],
        [0., 0.]])


In [ ]:
# create a tensor with random values
