In [2]:
# these are the basic operations of tensorflow

import tensorflow as tf
# get the version of the tensorflow
print(tf.__version__)



2023-02-22 17:28:44.668729: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-22 17:28:47.713980: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-22 17:28:47.714008: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-22 17:28:55.072841: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directo

2.11.0


2023-02-22 17:29:02.079670: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-02-22 17:29:02.092753: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-02-22 17:29:02.092827: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (codespaces-4bf78d): /proc/driver/nvidia/version does not exist
2023-02-22 17:29:02.107720: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
# create a constant tensor with the value 2 and 3 and print it out      

a = tf.constant(2)
b = tf.constant(3)
print(a)
print(b)



tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [8]:
# create array for 8x1 array 
c = tf.constant([2,3,4,5,6,7,8,9])
print(c)
# convert the array into 2x4 array
d = tf.reshape(c, [2,4])
print(d)



tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)
tf.Tensor(
[[2 3 4 5]
 [6 7 8 9]], shape=(2, 4), dtype=int32)


In [7]:
# create a function to add two numbers
add = tf.add(a, b)
# create a function to multiply two numbers
mul = tf.multiply(a, b)

# create a metrix with the value 1, 2, 3, 4
matrix1 = tf.constant([[1, 2], [3, 4]])
# create a metrix with the value 5, 6, 7, 8
matrix2 = tf.constant([[5, 6], [7, 8]])

print (matrix1)

# get the dot product of the two metrix
# the result is a metrix
# the result is a metrix
product = tf.matmul(matrix1, matrix2)
print (product) 

# get the dot product of the two metrix
# the result is a metrix
matrixdot= tf.tensordot(matrix1, matrix2, axes=1)
print (matrixdot)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
